version: '3.8'
services:
  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - app-network

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - client_node_modules:/app/node_modules
      - ./client/src/:/app/src/

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mariadb
    env_file:
      - .db.env

  mariadb:
    image: mariadb:10.6.4
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    env_file:
      - .db.env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - client
      - api
      - socket

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
  client_node_modules:
